DROP TABLE CURRENCY;
CREATE TABLE CURRENCY (
                                        ID INT AUTO_INCREMENT PRIMARY KEY,
                                        CURRENCY_CODE VARCHAR(3) NOT NULL,
                                        CHINESE_NAME VARCHAR(50) NOT NULL,
                                        CREATE_TIME TIMESTAMP,
                                        UPDATE_TIME TIMESTAMP
);

INSERT INTO CURRENCY(CURRENCY_CODE,CHINESE_NAME,CREATE_TIME,UPDATE_TIME) VALUES ('USD', '美金', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO CURRENCY(CURRENCY_CODE,CHINESE_NAME,CREATE_TIME,UPDATE_TIME) VALUES ('GBP', '英鎊', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO CURRENCY(CURRENCY_CODE,CHINESE_NAME,CREATE_TIME,UPDATE_TIME) VALUES ('EUR', '歐元', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());